In [1]:
import tensorflow as tf
import numpy as np

C:\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
tensor_2d = np.array(np.random.rand(4, 4), dtype='float32')
tensor_2d_1 = np.array(np.random.rand(4, 4), dtype='float32')
tensor_2d_2 = np.array(np.random.rand(4, 4), dtype='float32')

In [3]:
m1 = tf.convert_to_tensor(tensor_2d)
m2 = tf.convert_to_tensor(tensor_2d_1)
m3 = tf.convert_to_tensor(tensor_2d_2)
mat_product = tf.matmul(m1, m2)
mat_sum = tf.add(m2, m3)
mat_det = tf.matrix_determinant(m3)

In [4]:
with tf.Session() as session:
    print(session.run(mat_product))
    print(session.run(mat_sum))
    print(session.run(mat_det))

[[0.41330767 0.36791688 1.0165449  0.67771304]
 [1.0029166  1.0602971  1.0846562  1.5339555 ]
 [0.46028447 0.49538833 0.5458244  0.71282977]
 [0.5725011  0.43248078 0.8553352  0.7943706 ]]
[[0.7967986  0.5346777  0.69821525 0.6680142 ]
 [0.60753405 0.96637034 1.3996315  0.9359075 ]
 [1.1104159  1.1318126  0.7358958  0.89402175]
 [0.45528507 0.46733963 0.7194044  1.1109136 ]]
0.0681089
