In [1]:
import tensorflow as tf

C:\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


### tf.zeros()

```tf.zeros(shape, dtype=tf.float32, name=None)```       
creates a tensor of shape and all elements will be zeros (when ran in session)

In [2]:
a = tf.zeros([2, 3], tf.int32)

In [3]:
with tf.Session() as sess:
    y = sess.run(a)

In [4]:
print(a)

Tensor("zeros:0", shape=(2, 3), dtype=int32)


In [5]:
print(y)

[[0 0 0]
 [0 0 0]]


### tf.zeros_like()

```tf.zeros_like(input_tensor, dtype=None, name=None, optimize=True)```        
creates a tensor of shape and type (unless type is specified) as the input_tensor but all elements are zeros.

In [6]:
b = tf.constant([[0, 1], [2, 3], [4, 5]], name="b")

In [7]:
b0 = tf.zeros_like(b)

In [8]:
with tf.Session() as sess:
    y = sess.run(b0)

In [9]:
print(y)

[[0 0]
 [0 0]
 [0 0]]
