In [1]:
import tensorflow as tf

C:\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


### tf.ones()

```tf.ones(shape, dtype=tf.float32, name=None)```

In [2]:
a = tf.ones([2, 3], tf.int32)

In [3]:
with tf.Session() as sess:
    y = sess.run(a)

In [4]:
print(y)

[[1 1 1]
 [1 1 1]]


### tf.ones_like()

```tf.ones_like(input_tensor, dtype=None, name=None, optimize=True)```

In [5]:
b = tf.constant([[0, 1], [2, 3], [4, 5]], name="b")

In [6]:
b1 = tf.ones_like(b)

In [7]:
with tf.Session() as sess:
    y = sess.run(b1)

In [8]:
print(y)

[[1 1]
 [1 1]
 [1 1]]
