In [1]:
import tensorflow as tf

C:\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


### tf.linspace()
```tf.linspace(start, stop, num, name=None)```   

In [2]:
a = tf.linspace(10.0, 13.0, 4)

In [3]:
with tf.Session() as sess:
    y = sess.run(a)
    print(y)

[10. 11. 12. 13.]


### tf.range()
```tf.range(start, limit=None, delta=1, dtype=None, name='range')```  

Eg 1:

In [4]:
b = tf.range(3, limit=18, delta=3, dtype=None, name='range')

In [5]:
with tf.Session() as sess:
    y = sess.run(b)
    print(y)

[ 3  6  9 12 15]


Eg 2:

In [6]:
c = tf.range(5)

In [7]:
with tf.Session() as sess:
    y = sess.run(c)
    print(y)

[0 1 2 3 4]
