In [1]:
import tensorflow as tf
import numpy as np

C:\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
def convert(v, t=tf.float32):
    return tf.convert_to_tensor(v, dtype=t)

In [3]:
m1 = convert(np.array(np.random.rand(4, 4), dtype='float32'))
m2 = convert(np.array(np.random.rand(4, 4), dtype='float32'))
m3 = convert(np.array(np.random.rand(4, 4), dtype='float32'))
m4 = convert(np.array(np.random.rand(4, 4), dtype='float32'))
m5 = convert(np.array(np.random.rand(4, 4), dtype='float32'))

In [4]:
m_tranpose = tf.transpose(m1)
m_mul = tf.matmul(m1, m2)
m_det = tf.matrix_determinant(m3)
m_inv = tf.matrix_inverse(m4)
m_solve = tf.matrix_solve(m5, [[1], [1], [1], [1]])

In [5]:
with tf.Session() as session:
    print(session.run(m_tranpose))
    print(session.run(m_mul))
    print(session.run(m_inv))
    print(session.run(m_det))
    print(session.run(m_solve))

[[0.3682642  0.7978085  0.8070538  0.67165536]
 [0.65931267 0.8877299  0.60784006 0.7246884 ]
 [0.6895274  0.95535773 0.8939838  0.24484082]
 [0.52734923 0.3491321  0.462596   0.01833919]]
[[1.2057041  1.9095683  0.8806881  1.1225181 ]
 [1.8828927  2.5690298  1.0693606  1.7114007 ]
 [1.7847173  2.380805   0.83556056 1.5367131 ]
 [1.0083694  1.3947484  0.7588531  1.0592405 ]]
[[  1.6894134    1.4098446    0.06959404  -7.2251163 ]
 [ -1.6122389   -5.755912    -0.7131035   23.550356  ]
 [  0.1014658    7.5447035    0.30768004 -15.528978  ]
 [  0.772302     4.0226846    1.6211435  -17.101574  ]]
0.18544172
[[ 0.03099902]
 [ 1.9465903 ]
 [ 0.4034313 ]
 [-0.5321802 ]]
