In [1]:
import tensorflow as tf
import numpy as np

C:\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
def convert(v, t=tf.float32):
    return tf.convert_to_tensor(v, dtype=t)

In [3]:
seg_ids = tf.constant([0, 0, 1, 2, 2])
tens1 = convert(np.array([(2, 5, 3, -5), (0, 3, -2, 5), (4, 3, 5, 3), (6, 1, 4, 0), (6, 1, 4, 0)]), tf.int32)
tens2 = convert(np.array([1, 2, 3, 4, 5]), tf.int32)

In [4]:
seg_sum = tf.segment_sum(tens1, seg_ids)
seg_sum_1 = tf.segment_sum(tens2, seg_ids)

In [5]:
with tf.Session() as session:
    print("Segmentation sum tens1: ")
    print(session.run(seg_sum))
    print("Segmentation sum tens2: ", session.run(seg_sum_1)) 

Segmentation sum tens1: 
[[ 2  8  1  0]
 [ 4  3  5  3]
 [12  2  8  0]]
Segmentation sum tens2:  [3 3 9]
