In [1]:
import numpy as np

a = np.random.randn(5)
print(a)

[-1.28122748 -0.16487814  1.14708397  0.1894055  -2.34329611]


In [2]:
print(a.shape)

(5,)


In [3]:
print(a.T)

[-1.28122748 -0.16487814  1.14708397  0.1894055  -2.34329611]


In [4]:
print(np.dot(a,a.T))

8.51144138175


In [5]:
a = np.random.randn(5,1)
print(a)

[[ 0.24082634]
 [-0.53326073]
 [-0.3990579 ]
 [ 0.4595233 ]
 [ 0.31230543]]


In [6]:
print(a.T)

[[ 0.24082634 -0.53326073 -0.3990579   0.4595233   0.31230543]]


In [7]:
print(np.dot(a,a.T))

[[ 0.05799733 -0.12842323 -0.09610366  0.11066532  0.07521138]
 [-0.12842323  0.284367    0.21280191 -0.24504573 -0.16654022]
 [-0.09610366  0.21280191  0.15924721 -0.18337641 -0.12462795]
 [ 0.11066532 -0.24504573 -0.18337641  0.21116166  0.14351162]
 [ 0.07521138 -0.16654022 -0.12462795  0.14351162  0.09753468]]


In [9]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b
print(c)

[[-0.31551672 -1.67635681 -1.56676007]
 [-0.15194074  0.01592677  1.99635333]]


In [11]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
print(c)

[[ 1.53445148  1.20567491 -0.57429593]
 [-0.02825688  1.24860178 -0.27979023]
 [-0.10285918 -0.21499606 -0.04147656]]


In [15]:
a = np.random.randn(3, 4)
b = np.random.randn(4, 1)
c = a + b.T
print(c)

[[ 1.01762933 -2.01288072  1.89087962  1.02076195]
 [ 0.6663651   0.60377242  0.42231545 -0.05381565]
 [ 0.87925728 -0.28968326  2.12329033  2.56383403]]
